function [isClass1,fTest,attenuation] = ...
    check_octaveFilter_class1(fs,f_center)

    G = 10^(3/10);

    ratios = [ ...
        G^-4 ...
        G^-3 ...
        G^-2 ...
        G^-1 ...
        G^(-3/8) ...
        G^(-1/4) ...
        G^(-1/8) ...
        1 ...
        G^(1/8) ...
        G^(1/4) ...
        G^(3/8) ...
        G^1 ...
        G^2 ...
        G^3 ...
        G^4];

    minAtt = [ ...
        70 ...
        60 ...
        40.5 ...
        16.6 ...
        -0.4 ...
        -0.4 ...
        -0.4 ...
        -0.4 ...
        -0.4 ...
        -0.4 ...
        -0.4 ...
        16.6 ...
        40.5 ...
        60 ...
        70];

    maxAtt = [ ...
        Inf ...
        Inf ...
        Inf ...
        Inf ...
        1.4 ...
        0.7 ...
        0.5 ...
        0.4 ...
        0.5 ...
        0.7 ...
        1.4 ...
        Inf ...
        Inf ...
        Inf ...
        Inf];

    fTest = f_center .* ratios;

    duration = 5;

    attenuation = nan(size(fTest));

    for k = 1:length(fTest)

        ft = fTest(k);

        if ft >= fs/2
            continue
        end

        t = (0:1/fs:duration-1/fs).';

        x = sin(2*pi*ft*t);

        y = octaveFilter_IEC(x,fs,f_center);

        trim = round(0.5*fs);

        if length(y) > 2*trim
            xEval = x(trim+1:end-trim);
            yEval = y(trim+1:end-trim);
        else
            xEval = x;
            yEval = y;
        end

        rmsIn = sqrt(mean(xEval.^2));
        rmsOut = sqrt(mean(yEval.^2));

        attenuation(k) = -20*log10(rmsOut/rmsIn);

    end

    valid = ~isnan(attenuation);

    isClass1 = all( ...
        attenuation(valid) >= minAtt(valid) & ...
        attenuation(valid) <= maxAtt(valid));

end