clear
clc
close all

%% Frequencies

f = [63 125 250 500 1000 2000 4000 8000];

%% Environmental conditions

T_C = 20;
RH = 70;
p = 101325;

%% ============================================================
%  CLOSE MICROPHONES - CALIBRATION
% =============================================================

calibAnglesDeg = ...
    [0 45 90 135 180 225 270 315];

d_p_close = ...
    [10 10 10 10 10 10 10 10];

h_s = 1.5;

h_r_close = ...
    [1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5];

d_close = sqrt( ...
    d_p_close.^2 + ...
    (h_s-h_r_close).^2);

G_s_close = ones(size(d_p_close));
G_m_close = ones(size(d_p_close));
G_r_close = ones(size(d_p_close));

D_surface_close = 0;

%% Close microphone measurements

Lp_total_close = [
    73.5 77.0 80.2 82.0 82.5 80.4 76.0 69.0
    72.8 76.4 79.6 81.5 82.0 79.9 75.5 68.7
    70.5 74.2 77.5 79.5 80.0 77.8 73.3 66.2
    69.8 73.4 76.8 78.8 79.4 77.0 72.7 65.5
    71.0 74.6 78.0 80.1 80.8 78.7 74.3 67.1
    72.0 75.6 79.0 81.1 81.7 79.5 75.1 68.0
    74.1 77.7 80.8 82.8 83.5 81.3 76.9 69.8
    74.5 78.0 81.2 83.2 83.9 81.8 77.4 70.2
];

Lp_bg_close = repmat( ...
    [45 45 44 43 42 41 40 39], ...
    length(calibAnglesDeg),1);

%% Estimate source LW and directivity

[L_W,L_W_std,L_W_mics,D_source, ...
 Lp_source_close,validBG_close] = ...
    estimate_Lw_from_close_mics( ...
        f, ...
        Lp_total_close, ...
        Lp_bg_close, ...
        d_close, ...
        d_p_close, ...
        h_s, ...
        h_r_close, ...
        G_s_close, ...
        G_m_close, ...
        G_r_close, ...
        T_C, ...
        RH, ...
        p, ...
        D_surface_close, ...
        calibAnglesDeg);

%% Display LW

fprintf('\n============================================\n')
fprintf('SOURCE CALIBRATION\n')
fprintf('============================================\n')

LwTable = table( ...
    f.', ...
    L_W.', ...
    L_W_std.', ...
    'VariableNames',{ ...
    'f_Hz', ...
    'L_W_dB', ...
    'Std_dB'});

disp(LwTable)

%% Display directivity

DirectivityTable = ...
    array2table( ...
        D_source, ...
        'VariableNames',compose('Hz_%d',f));

DirectivityTable.Angle_deg = ...
    calibAnglesDeg(:);

DirectivityTable = movevars( ...
    DirectivityTable, ...
    'Angle_deg', ...
    'Before',1);

disp(DirectivityTable)

%% ============================================================
%  FAR MICROPHONES
% =============================================================

theta_far = ...
    [20 60 140 230 310];

d_p_far = ...
    [100 150 200 250 300];

h_r_far = ...
    [1.5 1.5 1.5 1.5 1.5];

d_far = sqrt( ...
    d_p_far.^2 + ...
    (h_s-h_r_far).^2);

G_s_far = ...
    [1 1 1 1 1];

G_m_far = ...
    [1 1 1 1 1];

G_r_far = ...
    [1 1 1 1 1];

D_surface_far = 0;

%% Example barrier attenuation for each far microphone

A_bar_far = [
    0 0 0 0 0 0 0 0
    0 0 0 1 2 3 4 5
    0 0 1 3 5 7 9 11
    0 1 2 4 7 10 13 16
    1 2 3 6 9 12 16 20
];

%% Example far microphone measurements

Lp_total_far = [
    59 63 67 69 69 66 60 51
    56 60 64 66 65 61 54 44
    53 57 61 63 61 56 48 39
    50 54 58 59 56 50 42 35
    48 52 56 56 53 47 40 34
];

Lp_bg_far = repmat( ...
    [45 45 44 43 42 41 40 39], ...
    length(theta_far),1);

%% Validate all far microphones

results = validate_far_mics( ...
    f, ...
    L_W, ...
    calibAnglesDeg, ...
    D_source, ...
    Lp_total_far, ...
    Lp_bg_far, ...
    theta_far, ...
    d_far, ...
    d_p_far, ...
    h_s, ...
    h_r_far, ...
    G_s_far, ...
    G_m_far, ...
    G_r_far, ...
    T_C, ...
    RH, ...
    p, ...
    D_surface_far, ...
    A_bar_far);

%% ============================================================
%  DISPLAY RESULTS PER MICROPHONE
% =============================================================

for i = 1:length(theta_far)

    fprintf('\n============================================\n')
    fprintf('FAR MIC %d\n',i)
    fprintf('Angle = %.1f deg\n',theta_far(i))
    fprintf('Distance = %.2f m\n',d_far(i))
    fprintf('============================================\n')

    MicTable = table( ...
        f.', ...
        results.Lp_measured(i,:).', ...
        results.Lp_predicted(i,:).', ...
        results.Delta_L(i,:).', ...
        results.D_source_est(i,:).', ...
        results.A_atm(i,:).', ...
        results.A_gr(i,:).', ...
        results.A_bar(i,:).', ...
        results.valid(i,:).', ...
        'VariableNames',{ ...
        'f_Hz', ...
        'Lp_measured', ...
        'Lp_predicted', ...
        'Delta_L', ...
        'D_source', ...
        'A_atm', ...
        'A_gr', ...
        'A_bar', ...
        'Valid'});

    disp(MicTable)

    fprintf('A_div = %.3f dB\n', ...
        results.A_div(i))

    fprintf('Bias = %.3f dB\n', ...
        results.Bias(i))

    fprintf('MAE = %.3f dB\n', ...
        results.MAE(i))

    fprintf('RMSE = %.3f dB\n', ...
        results.RMSE(i))

    fprintf('Measured = %.3f dBA\n', ...
        results.LpA_measured(i))

    fprintf('Predicted = %.3f dBA\n', ...
        results.LpA_predicted(i))

    fprintf('Delta LA = %.3f dB\n', ...
        results.Delta_LA(i))

end

%% ============================================================
%  OVERALL MICROPHONE SUMMARY
% =============================================================

fprintf('\n============================================\n')
fprintf('FAR MICROPHONE SUMMARY\n')
fprintf('============================================\n')

SummaryTable = table( ...
    (1:length(theta_far)).', ...
    theta_far.', ...
    d_far.', ...
    results.Bias, ...
    results.MAE, ...
    results.RMSE, ...
    results.LpA_measured, ...
    results.LpA_predicted, ...
    results.Delta_LA, ...
    'VariableNames',{ ...
    'Mic', ...
    'Angle_deg', ...
    'Distance_m', ...
    'Bias_dB', ...
    'MAE_dB', ...
    'RMSE_dB', ...
    'Measured_dBA', ...
    'Predicted_dBA', ...
    'Delta_dBA'});

disp(SummaryTable)

%% ============================================================
%  ERROR BY FREQUENCY
% =============================================================

fprintf('\n============================================\n')
fprintf('ERROR BY FREQUENCY\n')
fprintf('============================================\n')

FrequencyTable = table( ...
    f.', ...
    results.Bias_freq.', ...
    results.MAE_freq.', ...
    results.RMSE_freq.', ...
    'VariableNames',{ ...
    'f_Hz', ...
    'Bias_dB', ...
    'MAE_dB', ...
    'RMSE_dB'});

disp(FrequencyTable)

%% ============================================================
%  PLOTS
% =============================================================

figure

for i = 1:length(theta_far)

    semilogx( ...
        f, ...
        results.Lp_measured(i,:), ...
        'o-', ...
        'LineWidth',1.2)

    hold on

    semilogx( ...
        f, ...
        results.Lp_predicted(i,:), ...
        '--', ...
        'LineWidth',1.2)

end

grid on

xlabel('Frequency [Hz]')
ylabel('Sound Pressure Level [dB]')

title('Measured vs Predicted - Far Microphones')

%% Error spectra

figure

for i = 1:length(theta_far)

    semilogx( ...
        f, ...
        results.Delta_L(i,:), ...
        'o-', ...
        'LineWidth',1.2)

    hold on

end

yline(0,'--')

grid on

xlabel('Frequency [Hz]')
ylabel('\DeltaL = Measured - Predicted [dB]')

title('Prediction Error by Microphone')

%% Error statistics by frequency

figure

semilogx( ...
    f, ...
    results.Bias_freq, ...
    'o-', ...
    'LineWidth',1.5)

hold on

semilogx( ...
    f, ...
    results.MAE_freq, ...
    's-', ...
    'LineWidth',1.5)

semilogx( ...
    f, ...
    results.RMSE_freq, ...
    '^-', ...
    'LineWidth',1.5)

yline(0,'--')

grid on

xlabel('Frequency [Hz]')
ylabel('Error [dB]')

legend( ...
    'Bias', ...
    'MAE', ...
    'RMSE', ...
    'Location','best')

title('Validation Statistics by Frequency')