fprintf('\n')
fprintf('============================================================\n')
fprintf(' ISO 9613-2 MODEL - VALIDITY AND WORKING ASSUMPTIONS\n')
fprintf('============================================================\n')

fprintf('\nSTANDARD APPLICATION:\n')
fprintf('  - Outdoor propagation from ground-based noise sources.\n')
fprintf('  - Intended for road, rail, industrial, construction and similar sources.\n')
fprintf('  - Not intended for aircraft in flight, blast waves, military/mining blasts,\n')
fprintf('    or similar impulsive propagation phenomena.\n')

fprintf('\nFREQUENCY RANGE:\n')
fprintf('  - Calculation uses octave bands:\n')
fprintf('    63, 125, 250, 500, 1000, 2000, 4000 and 8000 Hz.\n')
fprintf('  - ISO 9613-2 requires octave filters of at least IEC 61260 Class 2.\n')
fprintf('  - This project targets Class 1 filtering when available.\n')

fprintf('\nATMOSPHERIC ABSORPTION - ISO 9613-1:\n')
fprintf('  - Main reference temperature range: -20 C to +50 C.\n')
fprintf('  - Main reference relative humidity range: 10 %% to 100 %%.\n')
fprintf('  - Reference pressure for the standard tabulation: 101.325 kPa.\n')
fprintf('  - ISO 9613-1 covers approximately 50 Hz to 10 kHz for these conditions.\n')
fprintf('  - Therefore the project octave range 63 Hz to 8 kHz is within this range.\n')
fprintf('  - ISO 9613-2 notes 10 C and 70 %% RH as typical default atmospheric\n')
fprintf('    conditions when representative local data are unavailable.\n')
fprintf('  - Site-specific or long-term representative weather data are preferred.\n')

fprintf('\nMETEOROLOGICAL CONDITIONS:\n')
fprintf('  - Lp(DW) represents favourable/downwind propagation conditions.\n')
fprintf('  - Standard downwind condition: wind direction within approximately\n')
fprintf('    +/-45 deg of the source-to-receiver direction.\n')
fprintf('  - Typical wind speed: approximately 1 to 5 m/s.\n')
fprintf('  - Wind speed reference measurement height: approximately 3 to 11 m.\n')
fprintf('  - For long-term predictions, Cmet should be considered.\n')
fprintf('  - For a specific short-duration experiment, Cmet is normally not\n')
fprintf('    applied automatically in this project.\n')

fprintf('\nGROUND MODEL:\n')
fprintf('  - G = 0 represents acoustically hard ground.\n')
fprintf('  - G = 1 represents porous ground.\n')
fprintf('  - Intermediate values represent mixed ground conditions.\n')
fprintf('  - Separate Gs, Gm and Gr values are used for source, middle and\n')
fprintf('    receiver ground regions.\n')
fprintf('  - Ground-effect formulae have geometry limitations and are primarily\n')
fprintf('    applicable to approximately flat terrain.\n')
fprintf('  - Significant terrain screening is treated separately as diffraction.\n')

fprintf('\nBARRIER / DIFFRACTION MODEL:\n')
fprintf('  - A screening obstacle should form a closed surface without large gaps.\n')
fprintf('  - Required surface density for a barrier is at least 10 kg/m^2.\n')
fprintf('  - Barrier dimensions must be sufficiently large relative to wavelength.\n')
fprintf('  - 2D terrain calculations in this project model the dominant top path.\n')
fprintf('  - For relevant 3D geometry, lateral diffraction paths should also be used.\n')
fprintf('  - Ground and barrier attenuation must not be double-counted.\n')

fprintf('\nDIRECTIVITY:\n')
fprintf('  - Dc is treated as D_source + D_surface in this project.\n')
fprintf('  - D_source is identified experimentally from close microphones.\n')
fprintf('  - D_surface accounts for nearby reflecting surfaces.\n')
fprintf('  - Care must be taken not to include the same reflection/directivity\n')
fprintf('    effect twice.\n')

fprintf('\nSOURCE CHARACTERIZATION:\n')
fprintf('  - ISO 9613-2 normally assumes the source sound power Lw is known.\n')
fprintf('  - In this project Lw is estimated inversely from close microphones.\n')
fprintf('  - Close microphones should preferably have clear LOS and simple\n')
fprintf('    propagation geometry with no unmodelled barrier effects.\n')
fprintf('  - Far microphones are kept separate and used for validation.\n')

fprintf('\nBACKGROUND-NOISE CORRECTION:\n')
fprintf('  - Source and background levels are separated energetically.\n')
fprintf('  - This project accepts a frequency band only when:\n')
fprintf('      Lp_total - Lp_background >= 3 dB.\n')
fprintf('  - This 3 dB criterion is a project analysis rule, not an ISO 9613-2 limit.\n')

fprintf('\nISO 9613-2 ESTIMATED ACCURACY FOR BROADBAND Lp(DW):\n')
fprintf('  Mean source/receiver height 0 < h <= 5 m:\n')
fprintf('      distance < 100 m       : +/-3 dB\n')
fprintf('      100 m < distance < 1 km: +/-3 dB\n')
fprintf('  Mean source/receiver height 5 < h <= 30 m:\n')
fprintf('      distance < 100 m       : +/-1 dB\n')
fprintf('      100 m < distance < 1 km: +/-3 dB\n')
fprintf('  - No corresponding Table-4 accuracy is stated beyond 1 km.\n')
fprintf('  - These values do NOT include uncertainty in the source sound power Lw.\n')
fprintf('  - Local meteorology and topography can cause larger deviations.\n')
fprintf('  - The stated accuracy is an engineering estimate, not a guaranteed\n')
fprintf('    statistical confidence interval.\n')

fprintf('\nCURRENT MODEL EQUATION:\n')
fprintf('  Lp(f) = Lw(f) + D_source(f) + D_surface(f)\n')
fprintf('          - Adiv - Aatm(f) - Agr(f) - Abar(f)\n')

fprintf('\n============================================================\n\n')