clear
clc
close all

%% ============================================================
%  PATHS
% =============================================================

addpath(fullfile(pwd,'functions'));

%% ============================================================
%  GENERAL SETTINGS
% =============================================================

f = [63 125 250 500 1000 2000 4000 8000];
nFreq = length(f);

T_C = 20;
RH = 70;
p = 101325;
c = 343;

A_weight = ...
    [-26.2 -16.1 -8.6 -3.2 0 1.2 1.0 -1.1];

%% ============================================================
%  SOURCE MODEL
% =============================================================

% Synthetic source model for testing.
% Replace later with source_model.mat.

L_W = ...
    [94 98 101 103 104 102 98 92];

calibAnglesDeg = ...
    [0 120 240];

D_source = [
     2.0   2.0   3.0   4.0   5.0   5.0   4.0   3.0
    -1.0   0.0   0.0  -1.0  -2.0  -2.0  -3.0  -3.0
    -2.0  -2.0  -3.0  -3.0  -3.0  -2.0  -1.0   0.0
];

h_s = 1.5;

%% ============================================================
%  CREATE SYNTHETIC 3D TERRAIN
% =============================================================

xTerrain = -100:10:600;
yTerrain = -300:10:300;

[Xterrain,Yterrain] = ...
    meshgrid(xTerrain,yTerrain);

% Base slope
Zterrain = ...
    0.008*Xterrain;

% Main ridge
Zterrain = Zterrain + ...
    35*exp( ...
        -((Xterrain-230).^2)/(2*55^2) ...
        -((Yterrain-20).^2)/(2*120^2));

% Secondary hill
Zterrain = Zterrain + ...
    20*exp( ...
        -((Xterrain-410).^2)/(2*45^2) ...
        -((Yterrain+100).^2)/(2*65^2));

% Valley
Zterrain = Zterrain - ...
    12*exp( ...
        -((Xterrain-330).^2)/(2*70^2) ...
        -((Yterrain-80).^2)/(2*60^2));

% Small side hill
Zterrain = Zterrain + ...
    13*exp( ...
        -((Xterrain-150).^2)/(2*35^2) ...
        -((Yterrain+170).^2)/(2*45^2));

%% ============================================================
%  SOURCE LOCATION
% =============================================================

sourceX = 0;
sourceY = 0;

sourceGround = ...
    interp2( ...
        xTerrain, ...
        yTerrain, ...
        Zterrain, ...
        sourceX, ...
        sourceY);

S = ...
    [sourceX ...
     sourceY ...
     sourceGround+h_s];

%% ============================================================
%  TEST RECEIVERS
% =============================================================

receiverHeight = 1.5;

receiverXY = [
    150     0
    300     0
    500     0
    300   120
    300  -120
    500   180
    500  -180
];

nReceivers = size(receiverXY,1);

%% ============================================================
%  GROUND PARAMETERS
% =============================================================

G_s = 1;
G_m = 1;
G_r = 1;

D_surface = zeros(1,nFreq);

%% ============================================================
%  BACKGROUND
% =============================================================

[~,Lp_background,LpA_background,bgDescription] = ...
    get_background_spectrum_typical('rural');

%% ============================================================
%  STORAGE
% =============================================================

Lp_source_all = nan(nReceivers,nFreq);
Lp_total_all = nan(nReceivers,nFreq);

LpA_source_all = nan(nReceivers,1);
LpA_total_all = nan(nReceivers,1);

A_div_all = nan(nReceivers,nFreq);
A_atm_all = nan(nReceivers,nFreq);
A_gr_all = nan(nReceivers,nFreq);
A_bar_all = nan(nReceivers,nFreq);

D_source_all = nan(nReceivers,nFreq);

receiverXYZ = nan(nReceivers,3);

%% ============================================================
%  PREDICT EACH TEST RECEIVER
% =============================================================

fprintf('\n')
fprintf('============================================================\n')
fprintf(' 3D TERRAIN RECEIVER TEST\n')
fprintf('============================================================\n')

for i = 1:nReceivers

    %% Receiver position

    xr = receiverXY(i,1);
    yr = receiverXY(i,2);

    zGround = ...
        interp2( ...
            xTerrain, ...
            yTerrain, ...
            Zterrain, ...
            xr, ...
            yr);

    R = ...
        [xr ...
         yr ...
         zGround+receiverHeight];

    receiverXYZ(i,:) = R;

    %% Geometry

    dx = R(1)-S(1);
    dy = R(2)-S(2);

    d_p = sqrt(dx^2 + dy^2);
    d = norm(R-S);

    thetaDeg = ...
        mod(atan2d(dy,dx),360);

    %% Source directivity

    D_source_receiver = ...
        estimate_Dsource_at_angle( ...
            calibAnglesDeg, ...
            D_source, ...
            thetaDeg);

    D_source_all(i,:) = ...
        D_source_receiver;

    %% Geometrical divergence

    A_div_scalar = ...
        calc_Atten_div(d);

    A_div = ...
        A_div_scalar*ones(1,nFreq);

    %% Atmospheric absorption

    [A_atm,alpha] = ...
        calc_Atten_atm( ...
            f,T_C,RH,p,d);

    %% Ground attenuation

    [A_gr,~,~,~] = ...
        calc_Atten_gr( ...
            f, ...
            h_s, ...
            receiverHeight, ...
            d_p, ...
            G_s, ...
            G_m, ...
            G_r);

    %% ========================================================
    %  3D TERRAIN DIFFRACTION
    % =========================================================

    paths = ...
        find_terrain_diffraction_paths_3D( ...
            S, ...
            R, ...
            xTerrain, ...
            yTerrain, ...
            Zterrain);

    A_bar_top = nan(1,nFreq);
    A_bar_left = nan(1,nFreq);
    A_bar_right = nan(1,nFreq);

    %% Top path

    if isfield(paths,'top') && ...
       ~isempty(paths.top) && ...
       isfield(paths.top,'z')

        [A_bar_top,~,~,~,~] = ...
            calc_Atten_bar( ...
                f, ...
                c, ...
                paths.top.z, ...
                paths.top.e, ...
                paths.top.d_ss, ...
                paths.top.d_sr, ...
                d, ...
                A_gr, ...
                'top');

    end

    %% Left path

    if isfield(paths,'left') && ...
       ~isempty(paths.left) && ...
       isfield(paths.left,'z')

        [A_bar_left,~,~,~,~] = ...
            calc_Atten_bar( ...
                f, ...
                c, ...
                paths.left.z, ...
                paths.left.e, ...
                paths.left.d_ss, ...
                paths.left.d_sr, ...
                d, ...
                A_gr, ...
                'lateral');

    end

    %% Right path

    if isfield(paths,'right') && ...
       ~isempty(paths.right) && ...
       isfield(paths.right,'z')

        [A_bar_right,~,~,~,~] = ...
            calc_Atten_bar( ...
                f, ...
                c, ...
                paths.right.z, ...
                paths.right.e, ...
                paths.right.d_ss, ...
                paths.right.d_sr, ...
                d, ...
                A_gr, ...
                'lateral');

    end

    %% Combine diffraction paths

    A_bar = ...
        combine_diffraction_paths( ...
            A_bar_top, ...
            A_bar_left, ...
            A_bar_right);

    %% Prediction

    [Lp_source,D_source_check] = ...
        predict_Lp_at_mic( ...
            f, ...
            L_W, ...
            thetaDeg, ...
            calibAnglesDeg, ...
            D_source, ...
            D_surface, ...
            A_div, ...
            A_atm, ...
            A_gr, ...
            A_bar);

    %% Add background

    Lp_total = ...
        10*log10( ...
            10.^(Lp_source/10) + ...
            10.^(Lp_background/10));

    %% A weighting

    LpA_source = ...
        10*log10(sum( ...
            10.^((Lp_source+A_weight)/10)));

    LpA_total = ...
        10*log10(sum( ...
            10.^((Lp_total+A_weight)/10)));

    %% Store

    Lp_source_all(i,:) = Lp_source;
    Lp_total_all(i,:) = Lp_total;

    LpA_source_all(i) = LpA_source;
    LpA_total_all(i) = LpA_total;

    A_div_all(i,:) = A_div;
    A_atm_all(i,:) = A_atm;
    A_gr_all(i,:) = A_gr;
    A_bar_all(i,:) = A_bar;

    %% Print

    fprintf('\nReceiver %d\n',i)
    fprintf('-----------------------------\n')
    fprintf('X = %.2f m\n',R(1))
    fprintf('Y = %.2f m\n',R(2))
    fprintf('Ground Z = %.2f m\n',zGround)
    fprintf('Receiver Z = %.2f m\n',R(3))
    fprintf('Horizontal distance = %.2f m\n',d_p)
    fprintf('Direct distance = %.2f m\n',d)
    fprintf('Angle = %.2f deg\n',thetaDeg)

    fprintf('Source only = %.2f dBA\n',LpA_source)
    fprintf('Background = %.2f dBA\n',LpA_background)
    fprintf('Total = %.2f dBA\n',LpA_total)

end

%% ============================================================
%  RECEIVER SUMMARY
% =============================================================

ReceiverSummary = table( ...
    (1:nReceivers).', ...
    receiverXYZ(:,1), ...
    receiverXYZ(:,2), ...
    receiverXYZ(:,3), ...
    LpA_source_all, ...
    LpA_total_all, ...
    'VariableNames',{ ...
        'Receiver', ...
        'X_m', ...
        'Y_m', ...
        'Z_m', ...
        'Source_dBA', ...
        'Total_dBA'});

fprintf('\n')
fprintf('============================================================\n')
fprintf(' RECEIVER SUMMARY\n')
fprintf('============================================================\n')

disp(ReceiverSummary)

%% ============================================================
%  TERRAIN + RECEIVERS PLOT
% =============================================================

figure

surf( ...
    Xterrain, ...
    Yterrain, ...
    Zterrain, ...
    'EdgeColor','none')

hold on

plot3( ...
    S(1), ...
    S(2), ...
    S(3), ...
    'o', ...
    'MarkerSize',10, ...
    'LineWidth',2)

plot3( ...
    receiverXYZ(:,1), ...
    receiverXYZ(:,2), ...
    receiverXYZ(:,3), ...
    's', ...
    'MarkerSize',8, ...
    'LineWidth',1.5)

grid on
axis equal

xlabel('X [m]')
ylabel('Y [m]')
zlabel('Elevation [m]')

title('3D Terrain, Source and Test Receivers')

view(45,30)

%% ============================================================
%  RECEIVER SPECTRA
% =============================================================

figure
hold on

for i = 1:nReceivers

    semilogx( ...
        f, ...
        Lp_source_all(i,:), ...
        'o-', ...
        'LineWidth',1.2, ...
        'DisplayName',sprintf('Receiver %d',i));

end

grid on

xlabel('Frequency [Hz]')
ylabel('L_p source [dB]')

title('Predicted source spectrum at receivers')

legend('Location','best')

%% ============================================================
%  ATTENUATION COMPARISON
% =============================================================

figure
hold on

for i = 1:nReceivers

    semilogx( ...
        f, ...
        A_bar_all(i,:), ...
        'o-', ...
        'LineWidth',1.2, ...
        'DisplayName',sprintf('Receiver %d',i));

end

grid on

xlabel('Frequency [Hz]')
ylabel('A_{bar} [dB]')

title('Terrain diffraction attenuation')

legend('Location','best')

%% ============================================================
%  NOISE MAP SETTINGS
% =============================================================

doNoiseMap = false;

mapSpacing = 25;

xRec = 25:mapSpacing:550;
yRec = -250:mapSpacing:250;

[Xrec,Yrec] = ...
    meshgrid(xRec,yRec);

LpA_map = nan(size(Xrec));

%% ============================================================
%  COMPUTE NOISE MAP
% =============================================================

if doNoiseMap

    fprintf('\n')
    fprintf('============================================================\n')
    fprintf(' CALCULATING NOISE MAP\n')
    fprintf('============================================================\n')

    nMapPoints = numel(Xrec);

    counter = 0;

    for row = 1:size(Xrec,1)

        for col = 1:size(Xrec,2)

            counter = counter + 1;

            xr = Xrec(row,col);
            yr = Yrec(row,col);

            zGround = ...
                interp2( ...
                    xTerrain, ...
                    yTerrain, ...
                    Zterrain, ...
                    xr, ...
                    yr);

            if isnan(zGround)
                continue
            end

            R = ...
                [xr ...
                 yr ...
                 zGround+receiverHeight];

            %% Geometry

            dx = R(1)-S(1);
            dy = R(2)-S(2);

            d_p = ...
                sqrt(dx^2 + dy^2);

            d = ...
                norm(R-S);

            thetaDeg = ...
                mod(atan2d(dy,dx),360);

            %% Directivity

            D_source_receiver = ...
                estimate_Dsource_at_angle( ...
                    calibAnglesDeg, ...
                    D_source, ...
                    thetaDeg);

            %% Propagation

            A_div_scalar = ...
                calc_Atten_div(d);

            A_div = ...
                A_div_scalar*ones(1,nFreq);

            [A_atm,~] = ...
                calc_Atten_atm( ...
                    f,T_C,RH,p,d);

            [A_gr,~,~,~] = ...
                calc_Atten_gr( ...
                    f, ...
                    h_s, ...
                    receiverHeight, ...
                    d_p, ...
                    G_s, ...
                    G_m, ...
                    G_r);

            %% Terrain diffraction

            paths = ...
                find_terrain_diffraction_paths_3D( ...
                    S, ...
                    R, ...
                    xTerrain, ...
                    yTerrain, ...
                    Zterrain);

            A_bar_top = nan(1,nFreq);
            A_bar_left = nan(1,nFreq);
            A_bar_right = nan(1,nFreq);

            if isfield(paths,'top') && ...
               ~isempty(paths.top) && ...
               isfield(paths.top,'z')

                [A_bar_top,~,~,~,~] = ...
                    calc_Atten_bar( ...
                        f,c, ...
                        paths.top.z, ...
                        paths.top.e, ...
                        paths.top.d_ss, ...
                        paths.top.d_sr, ...
                        paths.top.d, ...
                        A_gr, ...
                        'top');

            end

            if isfield(paths,'left') && ...
               ~isempty(paths.left) && ...
               isfield(paths.left,'z')

                [A_bar_left,~,~,~,~] = ...
                    calc_Atten_bar( ...
                        f,c, ...
                        paths.left.z, ...
                        paths.left.e, ...
                        paths.left.d_ss, ...
                        paths.left.d_sr, ...
                        paths.left.d, ...
                        A_gr, ...
                        'lateral');

            end

            if isfield(paths,'right') && ...
               ~isempty(paths.right) && ...
               isfield(paths.right,'z')

                [A_bar_right,~,~,~,~] = ...
                    calc_Atten_bar( ...
                        f,c, ...
                        paths.right.z, ...
                        paths.right.e, ...
                        paths.right.d_ss, ...
                        paths.right.d_sr, ...
                        paths.right.d, ...
                        A_gr, ...
                        'lateral');

            end

            A_bar = ...
                combine_diffraction_paths( ...
                    A_bar_top, ...
                    A_bar_left, ...
                    A_bar_right);

            %% Prediction

            Lp_source = ...
                L_W + ...
                D_source_receiver + ...
                D_surface - ...
                A_div - ...
                A_atm - ...
                A_gr - ...
                A_bar;

            %% A weighted source level

            LpA_source = ...
                10*log10(sum( ...
                    10.^((Lp_source+A_weight)/10)));

            %% Background + source

            Lp_total = ...
                10*log10( ...
                    10.^(Lp_source/10) + ...
                    10.^(Lp_background/10));

            LpA_total = ...
                10*log10(sum( ...
                    10.^((Lp_total+A_weight)/10)));

            LpA_map(row,col) = ...
                LpA_total;

        end

        fprintf( ...
            'Noise map row %d / %d completed\n', ...
            row,size(Xrec,1));

    end

end

%% ============================================================
%  2D NOISE MAP
% =============================================================

if doNoiseMap

    figure

    contourf( ...
        Xrec, ...
        Yrec, ...
        LpA_map, ...
        20, ...
        'LineColor','none');

    hold on

    plot( ...
        S(1), ...
        S(2), ...
        'o', ...
        'MarkerSize',9, ...
        'LineWidth',2)

    colorbar

    axis equal

    xlabel('X [m]')
    ylabel('Y [m]')

    title('Predicted Noise Map [dBA]')

end

%% ============================================================
%  NOISE MAP OVER TERRAIN
% =============================================================

if doNoiseMap

    Zrec = ...
        interp2( ...
            xTerrain, ...
            yTerrain, ...
            Zterrain, ...
            Xrec, ...
            Yrec);

    figure

    surf( ...
        Xterrain, ...
        Yterrain, ...
        Zterrain, ...
        'EdgeColor','none');

    hold on

    contour3( ...
        Xrec, ...
        Yrec, ...
        LpA_map, ...
        10, ...
        'LineWidth',1.5);

    plot3( ...
        S(1), ...
        S(2), ...
        S(3), ...
        'o', ...
        'MarkerSize',10, ...
        'LineWidth',2);

    xlabel('X [m]')
    ylabel('Y [m]')
    zlabel('Elevation [m]')

    grid on
    view(45,35)

    title('Terrain and Predicted Noise Contours')

end

%% ============================================================
%  EXPORT RESULTS
% =============================================================

outputExcel = ...
    fullfile(pwd,'terrain_3D_test_results.xlsx');

if isfile(outputExcel)
    delete(outputExcel)
end

writetable( ...
    ReceiverSummary, ...
    outputExcel, ...
    'Sheet','Receivers');

for i = 1:nReceivers

    ReceiverSpectrum = table( ...
        f.', ...
        D_source_all(i,:).', ...
        A_div_all(i,:).', ...
        A_atm_all(i,:).', ...
        A_gr_all(i,:).', ...
        A_bar_all(i,:).', ...
        Lp_source_all(i,:).', ...
        Lp_total_all(i,:).', ...
        'VariableNames',{ ...
            'f_Hz', ...
            'D_source', ...
            'A_div', ...
            'A_atm', ...
            'A_gr', ...
            'A_bar', ...
            'Lp_source', ...
            'Lp_total'});

    writetable( ...
        ReceiverSpectrum, ...
        outputExcel, ...
        'Sheet',sprintf('Receiver_%02d',i));

end

if doNoiseMap

    NoiseMapTable = table( ...
        Xrec(:), ...
        Yrec(:), ...
        LpA_map(:), ...
        'VariableNames',{ ...
            'X_m', ...
            'Y_m', ...
            'LpA_dBA'});

    writetable( ...
        NoiseMapTable, ...
        outputExcel, ...
        'Sheet','Noise Map');

end

fprintf('\n')
fprintf('============================================================\n')
fprintf(' TERRAIN TEST COMPLETE\n')
fprintf('============================================================\n')

fprintf('Results saved to:\n%s\n',outputExcel)